name: Book generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    uses: guillep/BookBuilderDashboard/.github/workflows/build-pillarbook-texlive23.yml@master
    with:
      bookname: vm-wip
